# Generated by Django 3.1.6 on 2021-02-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_name', models.CharField(max_length=100)),
                ('pd_price', models.IntegerField(default=0)),
            ],
        ),
    ]
