# Generated by Django 3.1.6 on 2021-02-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='staff_info',
            name='staff_phonenumber',
            field=models.CharField(max_length=50),
        ),
    ]
