# Generated by Django 3.1.6 on 2021-02-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='메뉴아이디')),
                ('menuname', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('price', models.IntegerField(verbose_name='가격')),
            ],
            options={
                'db_table': 'm_menu',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderno', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='주문번호')),
                ('orderdate', models.CharField(default='', max_length=10, verbose_name='주문일자(YYYY-MM-DD)')),
                ('ordertime', models.CharField(default='', max_length=10, verbose_name='주문시간(HH:MM:SS)')),
                ('payment', models.CharField(choices=[('card', '카드'), ('cash', '현금')], max_length=20, verbose_name='결제구분')),
                ('status', models.CharField(choices=[('done', '완료'), ('prep', '준비중'), ('ord', '주문')], max_length=20, verbose_name='완료여부')),
            ],
            options={
                'db_table': 'm_order',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.CharField(max_length=20, verbose_name='직원id')),
                ('staffname', models.CharField(max_length=20, verbose_name='직원명')),
                ('jobtitle', models.CharField(choices=[('J30', '사원'), ('J10', 'CEO'), ('J40', '인턴'), ('J20', '메니저'), ('J50', '아르바이트')], max_length=20, verbose_name='직급')),
                ('startdate', models.DateField(verbose_name='입사일')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
            ],
            options={
                'db_table': 'm_staff',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='사용자')),
                ('user_pwd', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('user_mail', models.CharField(max_length=100, verbose_name='이메일주소')),
            ],
            options={
                'db_table': 'm_user',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='타입')),
                ('code', models.CharField(max_length=100, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='코드명')),
            ],
            options={
                'db_table': 'm_info',
                'unique_together': {('type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('qty', models.IntegerField(default=0, verbose_name='수량')),
                ('sales', models.IntegerField(default=0, verbose_name='판매량')),
                ('menuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_menu', to='mapleApp.menu', verbose_name='메뉴')),
                ('orderno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orderno', to='mapleApp.order', verbose_name='주문번호')),
            ],
            options={
                'db_table': 'm_orderdetail',
                'unique_together': {('orderno', 'menuid')},
            },
        ),
    ]
