# Generated by Django 3.1.6 on 2021-02-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0002_sampleproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_info',
            name='staff_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
