# Generated by Django 3.1.5 on 2021-02-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0004_auto_20210202_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleproduct',
            old_name='product_name',
            new_name='pro_name',
        ),
        migrations.RenameField(
            model_name='sampleproduct',
            old_name='product_price',
            new_name='pro_price',
        ),
    ]
