# Generated by Django 3.1.6 on 2021-02-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0002_auto_20210209_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('prep', '준비중'), ('done', '완료'), ('ord', '주문')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='jobtitle',
            field=models.CharField(choices=[('J10', 'CEO'), ('J40', '인턴'), ('J50', '아르바이트'), ('J30', '사원'), ('J20', '메니저')], max_length=20),
        ),
    ]
